### ISSUE TITLE
Flat JSON ambiguity can lead to transaction/budget duplication during solrize step

### ISSUE THREAD

**Issue by akmiller01** [IATI/refresher#267]
**Brief Description**
The `explode_element` function makes assumptions about the number of transactions or budgets based on the structure of the flattened JSON. For the most part, transaction and budget elements are single-valued, but cases can occur where they are multivalued (mostly multiple vocabularies [in the case of sector code] or multiple languages [in the case of descriptions]). Where these multiple vocabularies or multiple languages expand the elements of the flattened JSON into lists, the `explode_element` function appends one copy of the single-valued elements per the multi-valued elements.

One example I found is this activity, which you can see has two transaction/sector elements, but one transaction: https://d-portal.org/q.xml?aid=GB-GOV-3-IP_TD

You can see the Unified Platform serializes this as two transactions:
```
{
  "responseHeader":{
    "zkConnected":true,
    "status":0,
    "QTime":0,
    "params":{
      "q":"iati_identifier:\"GB-GOV-3-IP_TD\"",
      "fl":"transaction_sector_code"}},
  "response":{"numFound":2,"start":0,"numFoundExact":true,"docs":[
      {
        "transaction_sector_code":["43010"]},
      {
        "transaction_sector_code":["FDEA"]}]
  }}
  ```
  
 The best way to solve this parsing ambiguity, in my opinion, is to work from the hierarchical JSON (`fa['iati_json']`) https://github.com/IATI/refresher/blob/develop/src/library/solrize.py#L184 which will have an explicit one transaction child element, instead of the entire `fa` pre-flattened object.

**Severity**
High

**Issue Location**
E.g. https://d-portal.org/q.xml?aid=GB-GOV-3-IP_TD

**Steps to Reproduce**
Add a list of actions needed to replicate the error.
1. Go to `/datastore/transaction/select?q=iati_identifier:"GB-GOV-3-IP_TD"&fl=transaction_sector_code`
2. See duplicated transactions

**Expected Results/Behaviour**
Add details of what was supposed to happen according to the agreed User Story/ Acceptance Criteria.

**Actual Results/Behaviour**
Add a comprehensive description of what is happening. Include screenshots if applicable.

**Comment by odscjames** [comment]
I can see the current situation is bad because the amount would then be double counted if summing up transactions or looking at transactions grouped by another field.

But I think I need to have a chat to some people about what the expected results are here. 

Is the expected result:  One document exists in the transaction Solr core, with the "transaction_sector_code" field == ["FDEA","43010"] ?

Does the fact we have different transaction_sector_code vocabularies in this example complicate this?

What are the user stories for people searching the transactions data by transaction_sector_code and will this mess those up?

Note: http://dashboard.iatistandard.org/publisher/fcdo.html is publisher

**Comment by stevieflow** [comment]
Thanks @Alex @odscjames 

Certainly, at the ``transaction`` level, having multiple ``sector`` codes - so long as they are from different ``vocabulary`` - is permitted (or - perhaps it's clearer to say they are not overtly prohibited)

I actually helped FCDO prepare that file too!  I think the use case is when internal vocabularies might legitimately sit alongside more common ones.  Certainly , the intention is not to duplicate the _values_ - although it is also true that the whole value of each transaction will apply to each vocabulary (in light of the above logic)

Hence, it would be true that comparing transactions values across these two sector codes (from different vocabularies) would be a form of double counting, but the query would be peculiar if it expected a split / alignment of values.

@akmiller01 related to this, do you know if the same logic applies to other items at the ``transaction`` level?  ``aid-type`` is a good example, as[ publishers such as this one](http://d-portal.org/savi/?aid=XM-DAC-41121-2023-EUR-UKR) are using this to express multiple things, using various vocabularies (with ``aid-type``):

```
<transaction ref="G0072">
<transaction-type code="11"/>
<transaction-date iso-date="2023-03-10"/>
<value currency="DKK" value-date="2023-03-10">7000000</value>
<description>
<narrative xml:lang="EN">Ukraine Flash Appeal (FUKR22)</narrative>
</description>
<provider-org type="10">
<narrative xml:lang="EN">Government of the Faroe Islands</narrative>
</provider-org>
<aid-type code="3" vocabulary="2"/>
<aid-type code="B03" vocabulary="1"/>
<unhcr:value-USD>996583.144</unhcr:value-USD>
</transaction>
```

Just wondered if a similar outcome would exist for these ''aid-type''?

Appreciate my comment here doesn't solve the specific issue, but hopefully some contextual help

**Comment by akmiller01** [comment]
> Just wondered if a similar outcome would exist for these ''aid-type''?

Yes, the logic for splitting out the pre-flattened activity-level JSON into transaction and budget level would operate similarly on any instance where there's more than one value per field. The underlying issue is the ambiguity created when working on the pre-flattened JSON, because it's not technically possible to tell whether:
```
ref: "G0072",
aid_type_code: ["3", "B03"]
```

Is referring to one transaction with a ref and two aid type codes, or two transactions, one of which is missing a ref. So the best solution in my mind is to refer back to the hierarchically-serialized JSON, which will explicitly identify the number of transaction/budget child elements.

**Comment by odscjames** [comment]
A fix is now in testing on develop

**Comment by odscjames** [comment]
The example in this bug report is now correct in production data store
